---
title: "Contrast and Boosted Trees"
author: "Jerome Friedman"
date: '`r Sys.Date()`'
output:
  html_document:
  fig_caption: yes
  theme: cerulean
  toc: yes
  toc_depth: 2
vignette: >
  %\VignetteIndexEntry{conTree}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r echo=FALSE}
knitr::opts_chunk$set(
    message = FALSE,
    warning = FALSE,
    error = FALSE,
    tidy = FALSE,
    cache = FALSE
    )

## data generation
lgen <- function(n, f, s, dist) {
  if (dist == "logistic") {
    r <- runif(n)
    y <- f + s * log(r / (1 - r))
  }
  else if (dist == "normal") {
    y <- rnorm(n, f, 1.63107 * s)
  }
  else if (dist == "laplace") {
    y <- laplace(n, f, 1.585 * s)
  }
  else if (dist == "slash") {
    y <- f + 0.7522519 * s * rnorm(n) / runif(n)
  }
  else {
    stop("unsupported error distribution")
  }
  invisible(y)
}
datgen <- function(p = 10, no = 25000, scl = 0.5, sclf = 0.75, er = 2,
                   dist = "logistic", smax = 50) {
    x <- matrix(rnorm(p * no), ncol = p)
    b <- rnorm(p)
    b <- b / sqrt(sum(b**2))
    z <- er * runif(p)
    f <- rep(0, no)
    for (j in 1:p) {
      u <- sign(x[, j]) * abs(x[, j])**z[j]
      v <- sqrt(var(u))
      f <- f + b[j] * u / v
    }
    z <- er * runif(p)
    s <- rep(0, no)
    b <- rnorm(p)
    b <- b * sclf / sqrt(sum(b**2))
    for (j in 1:p) {
      u <- sign(x[, j]) * abs(x[, j])**z[j]
      v <- sqrt(var(u))
      s <- s + b[j] * u / v
    }
    s <- pmin(smax, scl * exp(s))
    y <- lgen(no, f, s, dist)
    invisible(list(x = x, y = y, f = f, s = s))
}

## predictions
lmpred <- function(x, lmm) {
  lmm$coefficients[1] + x %*% lmm$coefficients[2:length(lmm$coefficients)]
}

library("randomForest")

```

## Contrast demo


```{r}
library(conTree)

## generate training and test data sets
## n=25000, p=10, heteroskedastic logistic error
set.seed(12345)
d <- datgen(n = 5000)
e <- datgen(n = 5000)

## fit random forest (RF) model on training data
rf <- randomForest::randomForest(d$x, d$y)
##
## RF predicted values on test data
##
erf <- predict(rf, e$x)

## RF average absolute error from truth (e$f) on test data
cat(sprintf("RF mean absolute error: %f\n", mean(abs(e$f - erf))))

##
## fit linear model (LM) on training data
##
lmm <- lm(d$y ~ d$x)
##
## evaluate LM on test data
##
elm <- lmpred(e$x, lmm)
##
## LM average absolute error from truth (e$f) on test data
##
cat(sprintf("LM mean absolute error: %f\n", mean(abs(e$f - elm))))

##
## contrast y with RF predictions on test data
##
treerf <- contrast(e$x, e$y, erf, type = "diffmean")
##
## summarize terminal nodes
##
nodesum(treerf, e$x, e$y, erf)


##
## graphical summary
##
nodeplots(treerf, e$x, e$y, erf)

##
# x-region definitions for all terminal nodes
#
treesum(treerf)
#
# contrast y with LM predictions on test data
#
treelm <- contrast(e$x, e$y, elm, type = "diffmean")
nodesum(treelm, e$x, e$y, elm)
nodeplots(treelm, e$x, e$y, elm)
#
# contrast y with true f(x) on test data
#
treef <- contrast(e$x, e$y, e$f, type = "diffmean")
nodesum(treef, e$x, e$y, e$f)
nodeplots(treef, e$x, e$y, e$f)
#
# build contrast boosting (CB) model on training data
#
z0 <- rep(0, length(d$y))
mdl <- modtrast(d$x, d$y, z0, type = "diffmean", niter = 200)
#
# test set error vs iterations
#
xval(mdl, e$x, e$y, z0)
#
# CB model predictions on test data
#
ecb <- predtrast(mdl, e$x, z0)
#
# CB average absolute error from truth (e$f) on test data
#
mean(abs(e$f - ecb))
```

```{r}
#
# compare model lack-of-fit curves
# LM=black, RF=red, CB=blue, truth=green
#
treelm <- contrast(e$x, e$y, elm, type = "diffmean", tree.size = 50)
treerf <- contrast(e$x, e$y, erf, type = "diffmean", tree.size = 50)
treeecb <- contrast(e$x, e$y, ecb, type = "diffmean", tree.size = 50)
treef <- contrast(e$x, e$y, e$f, type = "diffmean", tree.size = 50)
lofcurve(treelm, e$x, e$y, elm)
u <- lofcurve(treerf, e$x, e$y, erf, doplot = 'none')
lines(u$x, u$y, col = "red")
u <- lofcurve(treeecb, e$x, e$y, ecb, doplot = 'none')
lines(u$x, u$y, col = "blue")
u <- lofcurve(treef, e$x, e$y, e$f, doplot = 'none')
lines(u$x, u$y, col = "green")
#
# contrast p(y | x) with p(z | x) = N(0,1) on test data
#
z <- rnorm(length(e$y))
tree <- contrast(d$x, d$y, z)
nodesum(tree, e$x, e$y, z)
nodeplots(tree, e$x, e$y, z)
#
# distribution boosting
# estimate full p(y | x) starting with p(z | x) = N(0,1)
#
```

## Now things work, if I use your fortran flags

```{r}

mdld <- modtrast(d$x, d$y, z, niter = 100)
#
# test set discrepancies vs iterations
#
xval(mdld, e$x, e$y, z)
#
# transform z-values to estimated y-values
#
tg <- predtrast(mdld, e$x, z)
#
# contrast transformed p(g(z)|x) with p(y|x) on test data
#
tree <- contrast(e$x, e$y, tg)

nodesum(tree, e$x, e$y, tg)
```

```{r}
nodeplots(tree, e$x, e$y, tg)
```

```{r}
#
# compute predicted p(g(z)|x)(black)and compare with
# true p(y|x)(red)for first nine test set observations
#
p <- ((1:100) - .5) / 100
q <- qnorm(p)
kk <- 1
par(mfrow = c(3, 3))
for (k in kk:(kk + 8)) {
  t <- ydist(mdld, e$x[k, ], q)
  plot(t, p, type = "l", xlim = c(-5, 5))
  lines(t, 1 / (1 + exp((e$f[k] - t) / e$s[k])), col = "red")
}
```

## Session Info


```{r}
sessionInfo()
```
