// Automatically generated by SUtools, editing not advised.
#ifndef R_CONTREE_H
#define R_CONTREE_H
#include <R.h>
#include <Rinternals.h>
#include <R_ext/Rdynload.h>
#ifdef ENABLE_NLS
#include <libintl.h>
#define _(String) dgettext ("contree", String)
#else
#define _(String) (String)
#endif

#define FDEF(name)  {#name, (DL_FUNC) &F77_SUB(name), sizeof(name ## _t)/sizeof(name ## _t[0]), name ##_t}
void F77_SUB(NA)(
int *no,
int *ni,
double *x,
double *y,
double *y2,
double *z,
double *w,
int *lx,
int *mxt,
int *itre,
double *rtre,
int *mxc,
double *cat,
int *ms,
int *isc
);
 
static R_NativePrimitiveArgType NA_t[] = {
INTSXP,
INTSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP,
INTSXP,
INTSXP,
INTSXP,
REALSXP,
INTSXP,
REALSXP,
INTSXP,
INTSXP
};
void F77_SUB(NA)(
double *x,
int *itre,
double *rtre,
double *cat,
double *yh
);
 
static R_NativePrimitiveArgType NA_t[] = {
REALSXP,
INTSXP,
REALSXP,
REALSXP,
REALSXP
};
void F77_SUB(dosort)(
int *no,
int *ni,
double *x,
double *w,
int *ms,
int *nu,
int *isc
);
 
static R_NativePrimitiveArgType dosort_t[] = {
INTSXP,
INTSXP,
REALSXP,
REALSXP,
INTSXP,
INTSXP,
INTSXP
};
void F77_SUB(NA)(
int *no,
int *ni,
double *x,
double *y,
double *y2,
double *z,
double *w,
int *lx,
int *m,
int *m1,
int *m2,
int *jt,
double *sp,
double *cri1,
double *cri2,
double *w1,
double *w2,
double *crm,
int *kct,
double *cat
);
 
static R_NativePrimitiveArgType NA_t[] = {
INTSXP,
INTSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP,
INTSXP,
INTSXP,
INTSXP,
INTSXP,
INTSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP,
INTSXP,
REALSXP
};
void F77_SUB(NA)(
double *x,
double *y,
double *y2,
double *z,
double *w,
int *m,
int *m1,
int *m2,
int *ntn,
double *pwr,
double *xmiss,
double *tp,
double *cri1s,
double *cri2s,
double *w1s,
double *w2s,
double *cri
);
 
static R_NativePrimitiveArgType NA_t[] = {
REALSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP,
INTSXP,
INTSXP,
INTSXP,
INTSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP
};
void F77_SUB(NA)(
double *x,
double *y,
double *y2,
double *z,
double *w,
int *m,
int *m1,
int *m2,
int *ntn,
double *pwr,
int *kct,
double *cat,
double *cri1,
double *cri2,
double *w1,
double *w2,
double *cri
);
 
static R_NativePrimitiveArgType NA_t[] = {
REALSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP,
INTSXP,
INTSXP,
INTSXP,
INTSXP,
REALSXP,
INTSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP
};
void F77_SUB(andarm)(
int *n,
double *y,
double *y2,
double *z,
double *w,
double *dst,
double *sw
);
 
static R_NativePrimitiveArgType andarm_t[] = {
INTSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP
};
void F77_SUB(set_kri)(
int *irg,
int *jrg
);
 
static R_NativePrimitiveArgType set_kri_t[] = {
INTSXP,
INTSXP
};
void F77_SUB(andarm11)(
int *n,
double *y,
double *z,
double *w,
double *dst,
double *sw
);
 
static R_NativePrimitiveArgType andarm11_t[] = {
INTSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP
};
void F77_SUB(andarm2)(
int *n,
double *y,
double *z,
double *w,
double *dst,
double *sw
);
 
static R_NativePrimitiveArgType andarm2_t[] = {
INTSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP
};
void F77_SUB(set_qqtrm)(
int *irg,
int *jrg
);
 
static R_NativePrimitiveArgType set_qqtrm_t[] = {
INTSXP,
INTSXP
};
void F77_SUB(andarm1)(
int *n,
double *y,
double *z,
double *w,
double *dst,
double *sw
);
 
static R_NativePrimitiveArgType andarm1_t[] = {
INTSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP
};
void F77_SUB(andarm3)(
int *n,
double *y,
double *z,
double *w,
double *dst,
double *sw
);
 
static R_NativePrimitiveArgType andarm3_t[] = {
INTSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP
};
void F77_SUB(andarm7)(
int *n,
double *y,
double *z,
double *w,
double *dst,
double *sw
);
 
static R_NativePrimitiveArgType andarm7_t[] = {
INTSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP
};
void F77_SUB(andarm12)(
int *n,
double *y,
double *z,
double *w,
double *dst,
double *sw
);
 
static R_NativePrimitiveArgType andarm12_t[] = {
INTSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP
};
void F77_SUB(andarm14)(
int *n,
double *y,
double *z,
double *w,
double *dst,
double *sw
);
 
static R_NativePrimitiveArgType andarm14_t[] = {
INTSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP
};
void F77_SUB(andarm8)(
int *n,
double *y,
double *z,
double *w,
double *dst,
double *sw
);
 
static R_NativePrimitiveArgType andarm8_t[] = {
INTSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP
};
void F77_SUB(andarm4)(
int *n,
double *y,
double *z,
double *w,
double *dst,
double *sw
);
 
static R_NativePrimitiveArgType andarm4_t[] = {
INTSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP
};
void F77_SUB(andarm5)(
int *n,
double *y,
double *z,
double *w,
double *dst,
double *sw
);
 
static R_NativePrimitiveArgType andarm5_t[] = {
INTSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP
};
void F77_SUB(andarm6)(
int *n,
double *y,
double *y2,
double *z,
double *w,
double *dst,
double *sw
);
 
static R_NativePrimitiveArgType andarm6_t[] = {
INTSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP
};
void F77_SUB(andarm15)(
int *n,
double *y,
double *y2,
double *z,
double *w,
double *dst,
double *sw
);
 
static R_NativePrimitiveArgType andarm15_t[] = {
INTSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP
};
void F77_SUB(andarm10)(
int *n,
double *y,
double *z,
double *w,
double *dst,
double *sw
);
 
static R_NativePrimitiveArgType andarm10_t[] = {
INTSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP
};
void F77_SUB(cendst)(
int *n,
double *y,
double *z,
double *w,
int *nit,
double *thr,
double *xmiss,
double *dst,
double *sw
);
 
static R_NativePrimitiveArgType cendst_t[] = {
INTSXP,
REALSXP,
REALSXP,
REALSXP,
INTSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP
};
void F77_SUB(cendst1)(
int *n,
double *y,
double *z,
double *w,
int *nit,
double *thr,
double *xmiss,
double *dst,
double *sw
);
 
static R_NativePrimitiveArgType cendst1_t[] = {
INTSXP,
REALSXP,
REALSXP,
REALSXP,
INTSXP,
REALSXP,
REALSXP,
REALSXP,
REALSXP
};
void F77_SUB(getcdf1)(
int *n,
double *y,
double *w,
int *nit,
double *thr,
double *xmiss,
int *nsamp,
int *m,
double *b,
double *cdf,
double *sw
);
 
static R_NativePrimitiveArgType getcdf1_t[] = {
INTSXP,
REALSXP,
REALSXP,
INTSXP,
REALSXP,
REALSXP,
INTSXP,
INTSXP,
REALSXP,
REALSXP,
REALSXP
};
void F77_SUB(diffcdf)(
int *m,
double *cdf1,
double *cdf2,
double *dst
);
 
static R_NativePrimitiveArgType diffcdf_t[] = {
INTSXP,
REALSXP,
REALSXP,
REALSXP
};
void F77_SUB(unique)(
int *n,
double *y,
int *nu
);
 
static R_NativePrimitiveArgType unique_t[] = {
INTSXP,
REALSXP,
INTSXP
};
void F77_SUB(fintcdf1)(
int *n,
double *y,
int *m,
double *b,
double *w1,
int *nit,
double *thr,
double *cdf,
int *jt,
double *err
);
 
static R_NativePrimitiveArgType fintcdf1_t[] = {
INTSXP,
REALSXP,
INTSXP,
REALSXP,
REALSXP,
INTSXP,
REALSXP,
REALSXP,
INTSXP,
REALSXP
};
void F77_SUB(set_vrb)(
int *irg,
int *jrg
);
 
static R_NativePrimitiveArgType set_vrb_t[] = {
INTSXP,
INTSXP
};
void F77_SUB(cdfpoints1)(
int *m,
double *x,
int *n,
double *y,
double *w,
double *cdf
);
 
static R_NativePrimitiveArgType cdfpoints1_t[] = {
INTSXP,
REALSXP,
INTSXP,
REALSXP,
REALSXP,
REALSXP
};
void F77_SUB(sort)(
double *x,
int *n
);
 
static R_NativePrimitiveArgType sort_t[] = {
REALSXP,
INTSXP
};
void F77_SUB(classin)(
int *ient,
int *nclasssv,
double *costssv,
int *nout,
double *out
);
 
static R_NativePrimitiveArgType classin_t[] = {
INTSXP,
INTSXP,
REALSXP,
INTSXP,
REALSXP
};
void F77_SUB(reorg)(
int *ient,
int *n,
double *a,
double *b
);
 
static R_NativePrimitiveArgType reorg_t[] = {
INTSXP,
INTSXP,
REALSXP,
REALSXP
};
void F77_SUB(NA)(
int *itr,
double *rtr,
int *mxnodes,
int *node,
int *nodes,
double *cri,
double *wt
);
 
static R_NativePrimitiveArgType NA_t[] = {
INTSXP,
REALSXP,
INTSXP,
INTSXP,
INTSXP,
REALSXP,
REALSXP
};
void F77_SUB(NA)(
int *itr,
double *rtr,
int *nodes,
double *thr,
int *itro,
double *rtro
);
 
static R_NativePrimitiveArgType NA_t[] = {
INTSXP,
REALSXP,
INTSXP,
REALSXP,
INTSXP,
REALSXP
};
void F77_SUB(NA)(
int *itr,
double *rtr,
int *nodes,
double *thr
);
 
static R_NativePrimitiveArgType NA_t[] = {
INTSXP,
REALSXP,
INTSXP,
REALSXP
};
void F77_SUB(NA)(
double *x,
int *itre,
double *rtre,
double *cat,
int *node
);
 
static R_NativePrimitiveArgType NA_t[] = {
REALSXP,
INTSXP,
REALSXP,
REALSXP,
INTSXP
};
void F77_SUB(NA)(
int *no,
int *ni,
double *x,
int *itre,
double *rtre,
double *cat,
int *nodes
);
 
static R_NativePrimitiveArgType NA_t[] = {
INTSXP,
INTSXP,
REALSXP,
INTSXP,
REALSXP,
REALSXP,
INTSXP
};
void F77_SUB(getlims)(
int *node,
int *ni,
int *itr,
double *rtr,
double *cat,
int *nvar,
int *jvar,
double *vlims,
int *jerr
);
 
static R_NativePrimitiveArgType getlims_t[] = {
INTSXP,
INTSXP,
INTSXP,
REALSXP,
REALSXP,
INTSXP,
INTSXP,
REALSXP,
INTSXP
};
void F77_SUB(trans)(
int *ny,
double *y,
double *wy,
int *nz,
double *z,
double *wz,
int *nt,
double *t
);
 
static R_NativePrimitiveArgType trans_t[] = {
INTSXP,
REALSXP,
REALSXP,
INTSXP,
REALSXP,
REALSXP,
INTSXP,
REALSXP
};
void F77_SUB(qntl)(
int *n,
double *y,
double *w,
int *nq,
double *p,
double *q
);
 
static R_NativePrimitiveArgType qntl_t[] = {
INTSXP,
REALSXP,
REALSXP,
INTSXP,
REALSXP,
REALSXP
};
void F77_SUB(untie)(
int *n,
double *y,
double *u
);
 
static R_NativePrimitiveArgType untie_t[] = {
INTSXP,
REALSXP,
REALSXP
};
void F77_SUB(NA)(
int *iseed
);
 
static R_NativePrimitiveArgType NA_t[] = {
INTSXP
};
void F77_SUB(NA)(
double *v,
double *a,
int *ii,
int *jj
);
 
static R_NativePrimitiveArgType NA_t[] = {
REALSXP,
REALSXP,
INTSXP,
INTSXP
};

static R_FortranMethodDef fMethods[] = {
FDEF(NA) ,
FDEF(NA) ,
FDEF(dosort) ,
FDEF(NA) ,
FDEF(NA) ,
FDEF(NA) ,
FDEF(andarm) ,
FDEF(set_kri) ,
FDEF(andarm11) ,
FDEF(andarm2) ,
FDEF(set_qqtrm) ,
FDEF(andarm1) ,
FDEF(andarm3) ,
FDEF(andarm7) ,
FDEF(andarm12) ,
FDEF(andarm14) ,
FDEF(andarm8) ,
FDEF(andarm4) ,
FDEF(andarm5) ,
FDEF(andarm6) ,
FDEF(andarm15) ,
FDEF(andarm10) ,
FDEF(cendst) ,
FDEF(cendst1) ,
FDEF(getcdf1) ,
FDEF(diffcdf) ,
FDEF(unique) ,
FDEF(fintcdf1) ,
FDEF(set_vrb) ,
FDEF(cdfpoints1) ,
FDEF(sort) ,
FDEF(classin) ,
FDEF(reorg) ,
FDEF(NA) ,
FDEF(NA) ,
FDEF(NA) ,
FDEF(NA) ,
FDEF(NA) ,
FDEF(getlims) ,
FDEF(trans) ,
FDEF(qntl) ,
FDEF(untie) ,
FDEF(NA) ,
FDEF(NA) ,
{NULL, NULL, 0}
};

void R_init_contree(DllInfo *dll){
  R_registerRoutines(dll, NULL, NULL, fMethods, NULL);
  R_useDynamicSymbols(dll, FALSE);
}
#endif
